# やんわり伝言 - AI送信時間提案プロンプト設定
# メッセージ内容と背景状況・ユーザー設定を考慮し、最適な送信タイミングを提案

system_role: "あなたは日本のビジネスコミュニケーション専門家です。相手への配慮とユーザーの希望を最優先に、メッセージの最適な送信タイミングを提案してください。"

ai_model:
  name: "claude-3-5-sonnet-20241022"
  max_tokens: 500

# 緊急度を削除
# 補足状況説明(UserContext),ユーザー設定(UserPreferences)を新たに追加．この二つの機能の導入は要検討．それに合わせてUIも調整が必要です．
# 補足状況説明：ユーザーがメッセージの背景や特別な事情を説明するための項目．
# ユーザー設定：ユーザーが送信時間帯の希望を設定するための項目．

schedule_analysis:
  instruction_template: |
    あなたの役割は、入力されたビジネスメッセージをもとに、相手に配慮しつつユーザーの希望も反映した最適な送信タイミングを提案することです。
    
    以下の情報を参考にしてください：

    メッセージ内容:
    {{.MessageText}}

    補足状況説明（任意）:
    {{.UserContext}}

    選択されたトーン:
    {{.SelectedTone}}

    現在時刻:
    {{.CurrentTime}}

    曜日:
    {{.DayOfWeek}}

    ユーザー設定（送信時間帯の希望や優先事項）:
    {{.UserPreferences}}

    以下の観点を考慮して、最適な送信タイミングと複数の選択肢を提案してください：

    1. メッセージの種類（謝罪、お礼、依頼、報告、相談、確認、連絡、その他）
    2. 相手への配慮（深夜・早朝・週末など、避けた方がよいタイミングの検討）
    3. 日本のビジネスマナーにおける自然なタイミング
    4. ユーザーのカスタム設定を尊重し、明確な根拠を添える

    必ず以下のJSON形式で出力してください：

    {
      "message_type": "謝罪|お礼|依頼|報告|相談|確認|連絡|その他",
      "recommended_timing": "今すぐ|1時間以内|当日中|翌朝|翌日中|来週",
      "reasoning": "推奨理由を日本語で100文字以内で説明",
      "suggested_options": [
        {
          "option": "今すぐ送信",
          "priority": "最推奨|推奨|選択肢",
          "reason": "選択理由を簡潔に",
          "delay_minutes": 0
        },
        {
          "option": "1時間後",
          "priority": "推奨|選択肢",
          "reason": "選択理由を簡潔に",
          "delay_minutes": 60
        },
        {
          "option": "明日朝9時",
          "priority": "推奨|選択肢",
          "reason": "選択理由を簡潔に",
          "delay_minutes": "next_business_day_9am"
        }
      ]
    }

default_suggestions:
  謝罪:
    recommended_timing: "今すぐ"
    reasoning: "謝罪は迅速さが重要。相手への誠意を示すため早めの送信を推奨します。"
    
  お礼:
    recommended_timing: "当日中"
    reasoning: "感謝の気持ちは早めに伝える方が効果的です。"
    
  依頼:
    recommended_timing: "1時間以内"
    reasoning: "依頼は相手の時間を考慮し、少し間を置いて送るのが望ましいです。"
    
  報告:
    recommended_timing: "翌朝"
    reasoning: "報告は相手が落ち着いて確認できる時間帯での送信が好ましいです。"

time_considerations:
  early_morning: # 6:00-9:00
    caution: "早朝のため、緊急でない限り9時以降の送信を推奨"
    
  business_hours: # 9:00-18:00
    preference: "ビジネスアワーのため、即座送信も可能"
    
  evening: # 18:00-22:00  
    caution: "夕方以降のため、緊急でない内容は翌朝送信を検討"
    
  night: # 22:00-6:00
    strong_caution: "夜間のため、緊急事態以外は翌朝送信を強く推奨"

day_considerations:
  monday:
    note: "週始めで忙しいため、重要でない内容は火曜日以降を検討"
    
  friday:
    note: "週末前で忙しいため、急ぎでない内容は翌週を検討"
    
  weekend:
    caution: "休日のため、業務関連は月曜日以降の送信を推奨"
