#\!/bin/bash

echo "=== バックエンドログ確認方法 ==="
echo ""
echo "方法1: 現在のプロセスを停止して新しいターミナルで起動"
echo "  1. 現在のバックエンドプロセスを停止:"
echo "     kill 19406"
echo ""
echo "  2. 新しいターミナルを開いて以下のコマンドを実行:"
echo "     cd /Users/hinano/workspace/yanwari-message"
echo "     npm run dev:backend"
echo ""
echo "方法2: ログファイルがある場合（通常はない）"
echo "  tail -f backend.log"
echo ""
echo "方法3: システムログを確認（macOS）"
echo "  log stream --predicate 'process == \"main\"' --info"
echo ""
echo "=== 手順 ==="
echo "1. 新しいターミナルウィンドウを開く"
echo "2. cd /Users/hinano/workspace/yanwari-message"
echo "3. npm run dev:backend"
echo "4. ブラウザで受信トレイを表示"
echo "5. ターミナルにログが出力される"

