version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: yanwari-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - yanwari-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: yanwari-message

  mongo-express:
    image: mongo-express:latest
    container_name: yanwari-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb

volumes:
  yanwari-data: