version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: yanwari-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: yanwari-message
    volumes:
      - mongodb_data:/data/db
    networks:
      - yanwari-network

volumes:
  mongodb_data:

networks:
  yanwari-network:
    driver: bridge