blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/pandalize/agile/discussions
    about: General questions and discussions about the project
  - name: 📖 Documentation
    url: https://github.com/pandalize/agile/wiki
    about: Project documentation and guides